# Generated by Django 6.1 on 2026-08-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=500)),
                ('address_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('scheduled_at', models.DateTimeField(help_text='Желаемая дата/время выполнения')),
                ('deadline_at', models.DateTimeField(help_text='Крайний срок сдачи фотоотчёта')),
                ('urgency', models.CharField(choices=[('normal', 'Обычная'), ('urgent', 'Срочная')], default='normal', max_length=20)),
                ('spec_file', models.FileField(blank=True, help_text='Спецификация от Базис (PDF/фото)', null=True, upload_to='orders/specs/')),
                ('dimensions', models.CharField(blank=True, max_length=255)),
                ('modules_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bitrix_deal_id', models.CharField(blank=True, help_text='ID сделки в Bitrix24 (v2)', max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('client_contact_name', models.CharField(blank=True, max_length=255)),
                ('client_contact_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('published', 'Опубликована'), ('booked', 'Забронирована'), ('confirmed', 'Подтверждена админом'), ('in_progress', 'В работе'), ('report_uploaded', 'Фотоотчёт загружен'), ('rejected_for_rework', 'Отклонена (доработка)'), ('accepted', 'Принята менеджером'), ('closed', 'Закрыта'), ('cancelled', 'Отменена менеджером'), ('booking_revoked', 'Бронь снята'), ('disputed', 'Спор/рекламация')], default='new', max_length=30)),
                ('booked_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'История статуса заявки',
                'verbose_name_plural': 'История статусов заявок',
                'ordering': ['-created_at'],
            },
        ),
    ]
