# Generated by Django 6.1 on 2026-08-19 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_alter_furnituretype_name_and_more'),
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Адрес объекта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bitrix_deal_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID сделки в Bitrix24'),
        ),
        migrations.AlterField(
            model_name='order',
            name='booked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Забронирована'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_contact_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО клиента на объекте'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Закрыта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_orders', to=settings.AUTH_USER_MODEL, verbose_name='Сборщик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий/особые условия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подтверждена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline_at',
            field=models.DateTimeField(verbose_name='Крайний срок сдачи'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dimensions',
            field=models.CharField(blank=True, max_length=255, verbose_name='Габариты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='furniture_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='dictionaries.furnituretype', verbose_name='Тип мебели'),
        ),
        migrations.AlterField(
            model_name='order',
            name='modules_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество модулей'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость работы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='required_specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='dictionaries.specialization', verbose_name='Требуемая специализация'),
        ),
        migrations.AlterField(
            model_name='order',
            name='scheduled_at',
            field=models.DateTimeField(verbose_name='Желаемая дата/время выполнения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='spec_file',
            field=models.FileField(blank=True, null=True, upload_to='orders/specs/', verbose_name='Спецификация (Базис)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('published', 'Опубликована'), ('booked', 'Забронирована'), ('confirmed', 'Подтверждена админом'), ('in_progress', 'В работе'), ('report_uploaded', 'Фотоотчёт загружен'), ('rejected_for_rework', 'Отклонена (доработка)'), ('accepted', 'Принята менеджером'), ('closed', 'Закрыта'), ('cancelled', 'Отменена менеджером'), ('booking_revoked', 'Бронь снята'), ('disputed', 'Спор/рекламация')], default='new', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='urgency',
            field=models.CharField(choices=[('normal', 'Обычная'), ('urgent', 'Срочная')], default='normal', max_length=20, verbose_name='Срочность'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем изменено'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='from_status',
            field=models.CharField(blank=True, max_length=30, verbose_name='Из статуса'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='to_status',
            field=models.CharField(max_length=30, verbose_name='В статус'),
        ),
    ]
