# Generated by Django 6.1 on 2026-08-20 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_address_alter_order_address_lat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('new', 'Новая'), ('published', 'Опубликована'), ('booked', 'Забронирована'), ('confirmed', 'Подтверждена админом'), ('in_progress', 'В работе'), ('report_uploaded', 'Фотоотчёт загружен'), ('rejected_for_rework', 'Отклонена (доработка)'), ('accepted', 'Принята менеджером'), ('closed', 'Закрыта'), ('cancelled', 'Отменена менеджером'), ('booking_revoked', 'Бронь снята'), ('disputed', 'Спор/рекламация')], max_length=30, verbose_name='Предыдущий статус'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='to_status',
            field=models.CharField(choices=[('new', 'Новая'), ('published', 'Опубликована'), ('booked', 'Забронирована'), ('confirmed', 'Подтверждена админом'), ('in_progress', 'В работе'), ('report_uploaded', 'Фотоотчёт загружен'), ('rejected_for_rework', 'Отклонена (доработка)'), ('accepted', 'Принята менеджером'), ('closed', 'Закрыта'), ('cancelled', 'Отменена менеджером'), ('booking_revoked', 'Бронь снята'), ('disputed', 'Спор/рекламация')], max_length=30, verbose_name='Новый статус'),
        ),
    ]
