# Generated by Django 6.1 on 2026-08-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bitrix_additional_services_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Доп. услуги (Bitrix)'),
        ),
        migrations.AddField(
            model_name='order',
            name='bitrix_assembly_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Процент сборки, цеха, % (Bitrix)'),
        ),
        migrations.AddField(
            model_name='order',
            name='bitrix_delivery_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Доставка (Bitrix)'),
        ),
        migrations.AddField(
            model_name='order',
            name='bitrix_installation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Монтаж (Bitrix)'),
        ),
        migrations.AddField(
            model_name='order',
            name='bitrix_item_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма изделия (Bitrix)'),
        ),
        migrations.AddField(
            model_name='order',
            name='bitrix_lift_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Подъём (Bitrix)'),
        ),
    ]
