# Generated by Django 6.1 on 2026-08-19 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnituretype',
            name='photo_slots_template',
            field=models.ForeignKey(blank=True, help_text='Набор обязательных фото для этого типа мебели (п.10 ТЗ, вопрос №4)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='furniture_types', to='reports.photoslottemplate'),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='furniture_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_items', to='dictionaries.furnituretype'),
        ),
    ]
