# Generated by Django 6.1 on 2026-08-19 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_initial'),
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnituretype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='furnituretype',
            name='photo_slots_template',
            field=models.ForeignKey(blank=True, help_text='Набор обязательных фото для этого типа мебели (п.10 ТЗ, вопрос №4)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='furniture_types', to='reports.photoslottemplate', verbose_name='Шаблон фотоотчёта'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='furniture_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_items', to='dictionaries.furnituretype', verbose_name='Тип мебели'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название позиции'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
