# Generated by Django 6.1 on 2026-08-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_alter_furnituretype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnituretype',
            name='act_template_file',
            field=models.FileField(blank=True, help_text='Пустой бланк акта для этого типа мебели — менеджер заполняет и прикладывает по нему', null=True, upload_to='dictionaries/act_templates/', verbose_name='Бланк акта приёма-передачи'),
        ),
    ]
