# Generated by Django 6.1 on 2026-08-19 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDataAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('target_collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='collectors.collectorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
