# Generated by Django 6.1 on 2026-08-19 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0004_alter_collectorprofile_birth_date_and_more'),
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaldataaccesslog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Журнал доступа к персональным данным', 'verbose_name_plural': 'Журнал доступа к персональным данным'},
        ),
        migrations.AlterField(
            model_name='personaldataaccesslog',
            name='action',
            field=models.CharField(max_length=100, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='personaldataaccesslog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='personaldataaccesslog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес'),
        ),
        migrations.AlterField(
            model_name='personaldataaccesslog',
            name='target_collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='collectors.collectorprofile', verbose_name='Сборщик'),
        ),
        migrations.AlterField(
            model_name='personaldataaccesslog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='personaldataaccesslog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
