# Generated by Django 6.1 on 2026-08-21 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentrecord_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма к выплате')),
                ('method', models.CharField(choices=[('in_person', 'Лично в руки'), ('phone_transfer', 'Перевод по номеру телефона'), ('card_transfer', 'Перевод на карту')], max_length=20, verbose_name='Способ получения')),
                ('requisite', models.CharField(blank=True, help_text='Заполняется для перевода по карте или по номеру телефона', max_length=50, verbose_name='Номер карты/телефона')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий сборщика')),
                ('status', models.CharField(choices=[('pending', 'Ожидает звонка'), ('completed', 'Выплачено'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выплаты')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL, verbose_name='Сборщик')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_withdrawal_requests', to=settings.AUTH_USER_MODEL, verbose_name='Кто обработал')),
                ('payment_records', models.ManyToManyField(related_name='withdrawal_requests', to='payments.paymentrecord', verbose_name='Включённые начисления')),
            ],
            options={
                'verbose_name': 'Заявка на выплату',
                'verbose_name_plural': 'Заявки на выплату',
                'ordering': ['-created_at'],
            },
        ),
    ]
