# Generated by Django 6.1 on 2026-08-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MAX chat ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_via_max',
            field=models.BooleanField(default=False, verbose_name='Уведомления в MAX'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_via_telegram',
            field=models.BooleanField(default=True, verbose_name='Уведомления в Telegram'),
        ),
    ]
