# Generated by Django 6.1 on 2026-08-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_max_chat_id_user_notify_via_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_via_push',
            field=models.BooleanField(default=False, verbose_name='Push-уведомления в браузере'),
        ),
    ]
