# Generated by Django 6.1 on 2026-08-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=255)),
                ('profile_photo', models.ImageField(upload_to='collectors/profile_photos/')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('under_review', 'На проверке'), ('confirmed', 'Подтверждён'), ('rejected', 'Отклонён'), ('blocked', 'Заблокирован')], default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('tax_status', models.CharField(choices=[('individual', 'Физлицо'), ('self_employed', 'Самозанятый (НПД)'), ('sole_proprietor', 'ИП')], default='individual', max_length=20)),
                ('inn', models.CharField(blank=True, max_length=12)),
                ('ogrnip', models.CharField(blank=True, max_length=15)),
                ('npd_certificate', models.FileField(blank=True, null=True, upload_to='collectors/npd/')),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('has_own_tools', models.BooleanField(default=False)),
                ('tools_list', models.TextField(blank=True)),
                ('has_car', models.BooleanField(default=False)),
                ('willing_to_travel', models.BooleanField(default=False)),
                ('emergency_contact', models.CharField(blank=True, max_length=255)),
                ('personal_data_consent_given_at', models.DateTimeField(blank=True, null=True)),
                ('personal_data_consent_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Анкета сборщика',
                'verbose_name_plural': 'Анкеты сборщиков',
            },
        ),
        migrations.CreateModel(
            name='PassportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series_number', models.CharField(max_length=20)),
                ('issued_by', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('division_code', models.CharField(max_length=10)),
                ('registration_address', models.TextField()),
                ('actual_address', models.TextField()),
                ('scan_file', models.FileField(upload_to='collectors/passports/')),
            ],
            options={
                'verbose_name': 'Паспортные данные',
                'verbose_name_plural': 'Паспортные данные',
            },
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('card', 'Банковская карта / реквизиты'), ('sbp', 'СБП'), ('cash', 'Наличные')], default='card', max_length=20)),
                ('card_or_account_number', models.CharField(blank=True, max_length=34)),
                ('sbp_phone', models.CharField(blank=True, max_length=20)),
                ('cash_pickup_address', models.CharField(blank=True, max_length=255)),
                ('cash_pickup_time', models.CharField(blank=True, max_length=100)),
                ('cash_pickup_contact', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Реквизиты для оплаты',
                'verbose_name_plural': 'Реквизиты для оплаты',
            },
        ),
    ]
