# Generated by Django 6.1 on 2026-08-19 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collectors', '0001_initial'),
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorprofile',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectors', to='dictionaries.region'),
        ),
        migrations.AddField(
            model_name='collectorprofile',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='collectors', to='dictionaries.specialization'),
        ),
    ]
