# Generated by Django 6.1 on 2026-08-19 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collectors', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collector_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passportdata',
            name='collector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='collectors.collectorprofile'),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='collector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='collectors.collectorprofile'),
        ),
    ]
