# Generated by Django 6.1 on 2026-08-19 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0003_initial'),
        ('dictionaries', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectorprofile',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='birth_place',
            field=models.CharField(max_length=255, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=255, verbose_name='Контакт для экстренной связи'),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='experience_years',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Стаж работы (лет)'),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='has_car',
            field=models.BooleanField(default=False, verbose_name='Есть автомобиль'),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='has_own_tools',
            field=models.BooleanField(default=False, verbose_name='Есть свой инструмент'),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='inn',
            field=models.CharField(blank=True, max_length=12, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='npd_certificate',
            field=models.FileField(blank=True, null=True, upload_to='collectors/npd/', verbose_name='Справка НПД'),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='ogrnip',
            field=models.CharField(blank=True, max_length=15, verbose_name='ОГРНИП'),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='personal_data_consent_given_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Согласие на ПДн дано'),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='personal_data_consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP при согласии на ПДн'),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='profile_photo',
            field=models.ImageField(upload_to='collectors/profile_photos/', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectors', to='dictionaries.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Причина отклонения'),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='collectors', to='dictionaries.specialization', verbose_name='Специализации'),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('under_review', 'На проверке'), ('confirmed', 'Подтверждён'), ('rejected', 'Отклонён'), ('blocked', 'Заблокирован')], default='draft', max_length=20, verbose_name='Статус анкеты'),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='tax_status',
            field=models.CharField(choices=[('individual', 'Физлицо'), ('self_employed', 'Самозанятый (НПД)'), ('sole_proprietor', 'ИП')], default='individual', max_length=20, verbose_name='Налоговый статус'),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='tools_list',
            field=models.TextField(blank=True, verbose_name='Список инструмента'),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collector_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='collectorprofile',
            name='willing_to_travel',
            field=models.BooleanField(default=False, verbose_name='Готов к выездам в другие районы'),
        ),
        migrations.AlterField(
            model_name='passportdata',
            name='actual_address',
            field=models.TextField(verbose_name='Адрес фактического проживания'),
        ),
        migrations.AlterField(
            model_name='passportdata',
            name='collector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='collectors.collectorprofile', verbose_name='Сборщик'),
        ),
        migrations.AlterField(
            model_name='passportdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='passportdata',
            name='division_code',
            field=models.CharField(max_length=10, verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='passportdata',
            name='issue_date',
            field=models.DateField(verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='passportdata',
            name='issued_by',
            field=models.CharField(max_length=255, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='passportdata',
            name='registration_address',
            field=models.TextField(verbose_name='Адрес регистрации'),
        ),
        migrations.AlterField(
            model_name='passportdata',
            name='scan_file',
            field=models.FileField(upload_to='collectors/passports/', verbose_name='Скан паспорта'),
        ),
        migrations.AlterField(
            model_name='passportdata',
            name='series_number',
            field=models.CharField(max_length=20, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AlterField(
            model_name='passportdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='card_or_account_number',
            field=models.CharField(blank=True, max_length=34, verbose_name='Номер карты/реквизиты'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='cash_pickup_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес для передачи наличных'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='cash_pickup_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Контакт для передачи'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='cash_pickup_time',
            field=models.CharField(blank=True, max_length=100, verbose_name='Желаемое время передачи'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='collector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='collectors.collectorprofile', verbose_name='Сборщик'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='method',
            field=models.CharField(choices=[('card', 'Банковская карта / реквизиты'), ('sbp', 'СБП'), ('cash', 'Наличные')], default='card', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='sbp_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='СБП-номер телефона'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
