# Generated by Django 6.1 on 2026-08-20 10:18

import apps.collectors.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0004_alter_collectorprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passportdata',
            name='scan_file',
            field=models.FileField(storage=apps.collectors.storage.EncryptedPrivateStorage(), upload_to='%Y/%m/', verbose_name='Скан паспорта'),
        ),
    ]
