# Generated by Django 6.1 on 2026-08-20 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0005_alter_passportdata_scan_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorProfileChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('changes', models.JSONField(help_text='{"поле": "новое значение"}', verbose_name='Предлагаемые изменения')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('review_comment', models.TextField(blank=True, verbose_name='Комментарий рассмотрения')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='collectors.collectorprofile', verbose_name='Анкета')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='Кто рассмотрел')),
            ],
            options={
                'verbose_name': 'Заявка на изменение анкеты',
                'verbose_name_plural': 'Заявки на изменение анкет',
                'ordering': ['-created_at'],
            },
        ),
    ]
