# Generated by Django 6.1 on 2026-08-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0007_collectornote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectorprofile',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='passportdata',
            name='actual_address',
            field=models.TextField(blank=True, verbose_name='Адрес фактического проживания'),
        ),
        migrations.AlterField(
            model_name='passportdata',
            name='division_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='passportdata',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='passportdata',
            name='issued_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='passportdata',
            name='registration_address',
            field=models.TextField(blank=True, verbose_name='Адрес регистрации'),
        ),
        migrations.AlterField(
            model_name='passportdata',
            name='series_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Серия и номер паспорта'),
        ),
    ]
