# Generated by Django 6.1 on 2026-08-26 09:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0008_alter_collectorprofile_birth_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorprofile',
            name='block_reason',
            field=models.TextField(blank=True, verbose_name='Причина блокировки'),
        ),
        migrations.AddField(
            model_name='collectorprofile',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заблокирован до'),
        ),
        migrations.AddField(
            model_name='collectorprofile',
            name='rating_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))], verbose_name='Ручная корректировка рейтинга'),
        ),
    ]
