# Generated by Django 6.1 on 2026-08-26 10:54

import apps.collectors.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0009_collectorprofile_block_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportdata',
            name='registration_scan_file',
            field=models.FileField(default='', storage=apps.collectors.storage.EncryptedPrivateStorage(), upload_to='%Y/%m/', verbose_name='Скан страницы с пропиской'),
        ),
        migrations.AlterField(
            model_name='passportdata',
            name='scan_file',
            field=models.FileField(storage=apps.collectors.storage.EncryptedPrivateStorage(), upload_to='%Y/%m/', verbose_name='Скан паспорта (разворот с фото)'),
        ),
    ]
