# Generated by Django 6.1 on 2026-08-19 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_checked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Пункт чек-листа',
                'verbose_name_plural': 'Чек-лист',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to='reports/%Y/%m/')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='PhotoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Загружен'), ('accepted', 'Принят менеджером'), ('rejected', 'Отклонён (доработка)')], default='draft', max_length=20)),
                ('comment', models.TextField(blank=True, help_text='Комментарий сборщика')),
                ('manager_comment', models.TextField(blank=True, help_text='Комментарий менеджера при отклонении')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('geolocation_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geolocation_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Фотоотчёт',
                'verbose_name_plural': 'Фотоотчёты',
            },
        ),
        migrations.CreateModel(
            name='PhotoSlotDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Слот фото',
                'verbose_name_plural': 'Слоты фото',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PhotoSlotTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Шаблон фотоотчёта',
                'verbose_name_plural': 'Шаблоны фотоотчётов',
            },
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='acts/%Y/%m/')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='act', to='orders.order')),
            ],
            options={
                'verbose_name': 'Акт приёма-передачи',
                'verbose_name_plural': 'Акты приёма-передачи',
            },
        ),
    ]
