# Generated by Django 6.1 on 2026-08-19 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_address_alter_order_address_lat_and_more'),
        ('reports', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='act',
            name='file',
            field=models.FileField(upload_to='acts/%Y/%m/', verbose_name='Файл акта'),
        ),
        migrations.AlterField(
            model_name='act',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='act', to='orders.order', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='act',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='act',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Отмечен'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='reports.photoreport', verbose_name='Отчёт'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Пункт'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='reports/%Y/%m/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reports.photoreport', verbose_name='Отчёт'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='reports.photoslotdefinition', verbose_name='Слот'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='photoreport',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий сборщика'),
        ),
        migrations.AlterField(
            model_name='photoreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='photoreport',
            name='geolocation_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='photoreport',
            name='geolocation_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='photoreport',
            name='manager_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий менеджера'),
        ),
        migrations.AlterField(
            model_name='photoreport',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo_report', to='orders.order', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='photoreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Загружен'), ('accepted', 'Принят менеджером'), ('rejected', 'Отклонён (доработка)')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='photoreport',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='photoreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='photoslotdefinition',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='Обязателен'),
        ),
        migrations.AlterField(
            model_name='photoslotdefinition',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='photoslotdefinition',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='reports.photoslottemplate', verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='photoslotdefinition',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название слота'),
        ),
        migrations.AlterField(
            model_name='photoslottemplate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
