# Generated by Django 6.1 on 2026-08-20 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderstatushistory_changed_by_and_more'),
        ('reports', '0003_alter_act_created_at_alter_act_file_alter_act_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='is_readable_confirmed',
            field=models.BooleanField(default=False, help_text='Менеджер подтвердил, что все поля акта заполнены и разборчивы', verbose_name='Подтверждена читаемость'),
        ),
        migrations.CreateModel(
            name='AdditionalWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('description', models.CharField(max_length=255, verbose_name='Описание работы')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_works', to='orders.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Дополнительная работа',
                'verbose_name_plural': 'Дополнительные работы',
            },
        ),
    ]
