# Generated by Django 6.1 on 2026-08-26 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_act_is_readable_confirmed_additionalwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoreport',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='reports/videos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm'])], verbose_name='Видеоотчёт'),
        ),
    ]
