# Generated by Django 6.1 on 2026-08-26 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_photoreport_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='manager_act_file',
            field=models.FileField(blank=True, null=True, upload_to='acts/manager/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Акт от менеджера'),
        ),
        migrations.AddField(
            model_name='act',
            name='manager_act_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата загрузки акта менеджера'),
        ),
    ]
