# Generated by Django 6.1 on 2026-08-19 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('max', 'MAX')], default='telegram', max_length=20, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(max_length=100, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отправлено'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
