# Generated by Django 6.1 on 2026-08-21 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notificationlog_channel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Пусто — уведомление адресовано общему чату менеджеров/админов, не конкретному человеку', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
